import Providers from "@/lib/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ScrollToTopButton from "@/components/homePage/ScrollToTopButton/ScrollToTopButton";
import Navbar from "@/components/homePage/Navbar";
import { FooterLinks } from "@/components/homePage/Footer";

const inter = Inter({ subsets: ["latin-ext"] });

import { Layout } from "antd";
const { Header, Content, Footer } = Layout;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          {/* <Header> */}
          <Navbar />
          {/* </Header> */}
          {children}
          <FooterLinks />
          <ScrollToTopButton />
        </body>
      </html>
    </Providers>
  );
}
